gui:
  nerdFontsVersion: "3"
  showFileIcons: true
customCommands:
  - key: 'u'
    context: 'files'
    description: 'stash include untracked'
    command: 'git stash save --include-untracked "{{index .PromptResponses 0}}"'
    prompts:
      - type: 'input'
        title: 'Stash Message'
        initialValue: 'WIP'
  - key: '<c-c>'
    context: 'files'
    description: 'commit files with format'
    prompts:
      - type: 'menu'
        title: 'What kind of commit type is it?'
        key: 'Type'
        options:
          - name: 'feat'
            description: '新機能の追加'
            value: 'feat'
          - name: 'add'
            description: 'ライブラリとかの追加'
            value: 'add'
          - name: 'update'
            description: 'バグではない機能修正'
            value: 'update'
          - name: 'change'
            description: '仕様変更による機能修正'
            value: 'change'
          - name: 'remove'
            description: 'ファイルやコードの一部を削除'
            value: 'remove'
          - name: 'fix'
            description: 'バグや不具合の修正'
            value: 'fix'
          - name: 'revert'
            description: '修正の取り消し'
            value: 'revert'
          - name: 'rename'
            description: '名前の変更'
            value: 'rename'
          - name: 'docs'
            description: 'ドキュメントの更新や改善'
            value: 'docs'
          - name: 'comment'
            description: 'コメントの追加や編集'
            value: 'comment'
          - name: 'style'
            description: 'コードフォーマットの修正、UIのみの変更'
            value: 'style'
          - name: 'refactor'
            description: 'パフォーマンスの改善なしのコードの改善'
            value: 'refactor'
          - name: 'test'
            description: 'テストの追加や改善'
            value: 'test'
          - name: 'perf'
            description: 'パフォーマンスの改善'
            value: 'perf'
          - name: 'chore'
            description: 'ビルドプロセスの変更や改善'
            value: 'chore'
      - type: 'input'
        title: 'Enter the Message'
        key: 'Message'
        initialValue: ''
      - type: 'confirm'
        title: 'Commit'
        body: "Commit with the message '{{.Form.Type}}: {{.Form.Message}}'. Is this okay?"
    command: "bash -c 'type=\"{{.Form.Type}}\"; message=\"{{.Form.Message}}\"; commit_message=\"$type${scope:+($scope)}: $message\"; git commit -m \"$commit_message\"'"
    loadingText: 'Commiting...'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  allBranchesLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(#a0a0a0 reverse)%h%Creset %C(cyan)%ad%Creset %C(#dd4814)%ae%Creset %C(yellow reverse)%d%Creset %n%C(green bold)%s%Creset%n' --
  branchLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(#a0a0a0 reverse)%h%Creset %C(cyan)%ad%Creset %C(#dd4814)%ae%Creset %C(yellow reverse)%d%Creset %n%C(green bold)%s%Creset%n' {{branchName}} --
os:
  editPreset: 'nvim'
