cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "font-hack-nerd-font"
brew "fzf"
brew "git"
brew "git-delta"
brew "git-secrets"
brew "iterm2"
brew "mas"
brew "lazygit"
brew "mysql@5.7"
brew "neovim"
brew "nodenv"
brew "peco"
brew "redis"
brew "rbenv"
brew "ripgrep"
brew "tmux"
brew "typos-cli"
brew "wget"
brew "zoxide"
brew "zsh-autosuggestions"

cask "alt-tab"
cask "brave-browser"
cask "deepl"
cask "docker"
cask "google-chrome"
cask "google-drive"
cask "karabiner-elements"
cask "raycast"
cask "notion"
cask "postman"
cask "slack"
cask "visual-studio-code"
cask "warp"

# GitHub Actions ではインストールできない
# mas "CotEditor", id: 1024640650
# mas "Hidden Bar", id: 1452453066
# mas "Quick View Calendar", id: 1087080039
