require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.lazy")
require("utils.cursor").setup()
require("utils.ruby.spec_toggle").setup()
require("utils.ruby.spec_runner").setup()
