# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$custom\
[> ](fg:#88C0D0)\
\n$character
"""

right_format = """
$cmd_duration \
$username\
| \
$time
"""

[cmd_duration]
min_time = 1
format = '[$duration](bold yellow)'

[directory]
truncate_to_repo = false
truncation_symbol = "…/"
format = '[ $path ]($style)[$read_only]($read_only_style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '[(\[$staged$conflicted$stashed$deleted$renamed$modified$typechanged$untracked\])($ahead_behind)]($style) '
untracked = '?${count}'
modified = '*${count}'
deleted = '-${count}'
conflicted = '!${count}'
staged = '[+${count}](green)|'

[time]
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = 'user: [$user]($style) '
disabled = false
show_always = true

[custom.git_info]
when = 'git rev-parse --is-inside-work-tree >/dev/null 2>&1'
command = 'starship module git_branch && starship module git_status'
format = '\($output\)'
